services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  ollama-pull:
    image: ollama/ollama:latest
    container_name: ollama-pull
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=ollama:11434
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        echo "Esperando a que el servidor Ollama responda en el puerto 11434..."
        while ! (echo > /dev/tcp/ollama/11434) >/dev/null 2>&1; do
          sleep 3
        done
        echo "¡Conexión establecida! Iniciando descargas..."
        ollama pull gemma4:e2b
        echo "Descargas finalizadas."
    restart: "no"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - openwebui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
    name: ollama_data
  openwebui_data:
    name: openwebui_data
